version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
      - laravel_vendor:/var/www/html/vendor
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - laravel

  node:
    image: node:20
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - laravel_node_modules:/var/www/html/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel
    depends_on:
      - app

volumes:
  mysql_data:
  laravel_vendor:
  laravel_node_modules:

networks:
  laravel:
