name: Laravel Deployment with Vite Build Adjustment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust to match your project's PHP version
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.5' # Adjust to match your project's Node.js version

      - name: Install JavaScript dependencies
        run: npm install

      - name: Build Vite assets
        run: npm run build

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Set up Environment Variables
        run: |
          echo "IS_PRODUCTION=${{ secrets.F_IS_PRODUCTION }}" >> .env
          echo "DB_HOST=${{ secrets.F_DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ secrets.F_DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.F_DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.F_DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.F_DB_PORT }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.F_GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.F_GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.F_GOOGLE_CLIENT_REDIRECT }}" >> .env

      # Add any additional steps here if needed, like migrations or other pre-deployment tasks

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.H_SERVER }}
          username: ${{ secrets.H_USERNAME }}
          password: ${{ secrets.H_PASSWORD }}
