name: Laravel Deployment with Vite Build Adjustment

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.5'

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      - name: Move Build Folder
        run: mv public/build ../build

      - name: Set up Environment Variables
        run: |
          echo "IS_PRODUCTION=${{ secrets.F_IS_PRODUCTION }}" >> .env
          echo "DB_HOST=${{ secrets.F_DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ secrets.F_DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.F_DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.F_DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.F_DB_PORT }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.F_GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.F_GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.F_GOOGLE_CLIENT_REDIRECT }}" >> .env

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.H_SERVER }}
          username: ${{ secrets.H_USERNAME }}
          password: ${{ secrets.H_PASSWORD }}
